pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint
    joint_speed: 0.3
    motor:
        id: 10
        init: 512
        min: 0
        max: 4095
